const SYMBOLS={
 cherry:{name:'Cherry',icon:'🍒',base:5,weight:10,tags:['fruit'],description:'Стоимость 5. Пара: 10. Тройка: 30.'},
 lemon:{name:'Lemon',icon:'🍋',base:8,weight:10,tags:['fruit'],description:'Стоимость 8. Пара: 16. Тройка: 48.'},
 bell:{name:'Bell',icon:'🔔',base:12,weight:8,tags:[],description:'Стоимость 12. Пара: 24. Тройка: 72.'},
 diamond:{name:'Diamond',icon:'💎',base:10,weight:3,tags:['gem'],description:'Стоимость 10. Пара: 20. Тройка: 60. Gem Polish усиливает линию ×1.5.'},
 bomb:{name:'Bomb',icon:'💣',base:0,weight:5,tags:['destruction'],description:'Base 0, но совпавшая Bomb даёт +15 bonus за каждую Bomb.'},
 wild:{name:'Wild',icon:'★',base:0,weight:2,tags:['wild'],description:'Заменяет символ для пары/тройки, но сам добавляет 0 base points.'}
};
const MODIFIERS={
 fruitBasket:{name:'Fruit Basket',description:'Cherry и Lemon получают +4 стоимости.'},
 doubleGlass:{name:'Double Glass',description:'Если центральная клетка выигрышная, её стоимость добавляется ещё раз.'},
 gemPolish:{name:'Gem Polish',description:'Выигрышная линия Diamond получает ×1.5.'},
 scrapCollector:{name:'Scrap Collector',description:'Каждая активированная Bomb дополнительно даёт +2.'},
 echoChamber:{name:'Echo Chamber',description:'Первый bonus trigger линии повторяется ещё раз.'}
};
const STAGES=[120,180,260,380,550,800,1100,1600,2500];
const initialPool=()=>({cherry:3,lemon:2,bell:2,diamond:1,wild:1,bomb:0});
let state,forcedGrid=null;
function makeState(seed){return{seed:normalizeSeed(seed),rngState:normalizeSeed(seed),pool:initialPool(),modifiers:new Set(),stage:0,score:0,target:STAGES[0],spins:8,coins:20,lastScore:0,lastHits:new Set(),events:[],breakdown:[],reward:null,runComplete:false};}
function normalizeSeed(v){const n=Number(v);return Number.isFinite(n)?(Math.abs(Math.floor(n))>>>0)||1:1;}
function random(){state.rngState=(state.rngState+0x6D2B79F5)>>>0;let t=state.rngState;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;}
function weightedPick(){const es=Object.entries(state.pool).filter(([,c])=>c>0).map(([id,c])=>({id,weight:SYMBOLS[id].weight*c}));const total=es.reduce((s,e)=>s+e.weight,0);let r=random()*total;for(const e of es){r-=e.weight;if(r<=0)return e.id;}return es.at(-1).id;}
function makeGrid(){if(forcedGrid){const g=forcedGrid;forcedGrid=null;return g;}return Array.from({length:9},weightedPick);}
function symbolBase(id){let v=SYMBOLS[id].base;if(state.modifiers.has('fruitBasket')&&SYMBOLS[id].tags.includes('fruit'))v+=4;return v;}
function resolveLine(grid,indexes,row){const ids=indexes.map(i=>grid[i]),nonWild=ids.filter(id=>id!=='wild'),counts={};nonWild.forEach(id=>counts[id]=(counts[id]||0)+1);let candidate=null,best=0;for(const[id,c]of Object.entries(counts))if(c>best){candidate=id;best=c;}const wilds=ids.filter(id=>id==='wild').length;if(!candidate||best+wilds<2)return{score:0,matchedPositions:[],events:[],display:{row,symbols:ids.map(id=>SYMBOLS[id].icon).join(' '),title:'Нет комбинации',formula:'Нужно минимум 2 одинаковых символа',score:0}};const matched=indexes.filter((idx,l)=>ids[l]===candidate||ids[l]==='wild'),matchCount=Math.min(3,best+wilds),realValues=ids.filter(id=>id===candidate).map(()=>symbolBase(candidate)),wildValues=Array(wilds).fill(0),shownValues=[...realValues,...wildValues],rawBase=shownValues.reduce((a,b)=>a+b,0);let mult=matchCount===3?2:1;const events=[`LINE_MATCHED row=${row} ${SYMBOLS[candidate].name} x${matchCount}: base ${rawBase} × ${mult}`],notes=[];if(candidate==='diamond'&&state.modifiers.has('gemPolish')){mult*=1.5;notes.push('Gem Polish ×1.5');events.push('Gem Polish: Diamond line ×1.5');}let score=Math.floor(rawBase*mult),bonuses=[];if(candidate==='bomb'){let amount=best*15;if(state.modifiers.has('scrapCollector'))amount+=best*2;bonuses.push({name:`Bomb activation ×${best}`,amount});}if(state.modifiers.has('doubleGlass')&&matched.includes(4)&&grid[4]!=='wild')bonuses.push({name:'Double Glass',amount:symbolBase(grid[4])});if(state.modifiers.has('echoChamber')&&bonuses.length)bonuses.push({name:`Echo Chamber repeats ${bonuses[0].name}`,amount:bonuses[0].amount});for(const b of bonuses){score+=b.amount;notes.push(`${b.name} +${b.amount}`);events.push(`${b.name}: +${b.amount}`);}events.push(`SCORE_ADDED row=${row}: +${score}`);let formula=matchCount===3?`(${shownValues.join(' + ')}) × ${mult}`:shownValues.join(' + ');if(bonuses.length)formula+=` + ${bonuses.map(b=>b.amount).join(' + ')}`;return{score,matchedPositions:matched,events,display:{row,symbols:ids.map(id=>SYMBOLS[id].icon).join(' '),title:`${SYMBOLS[candidate].name} ×${matchCount}`,formula,notes,score}};}
function spin(){if(state.spins<=0||state.score>=state.target||state.runComplete)return;state.events=['SPIN_STARTED'];state.lastHits=new Set();state.reward=null;const grid=makeGrid();state.events.push(`GRID_CREATED rngState=${state.rngState}`);let total=0;state.breakdown=[];[[0,1,2],[3,4,5],[6,7,8]].forEach((line,row)=>{const r=resolveLine(grid,line,row+1);state.breakdown.push(r.display);total+=r.score;r.matchedPositions.forEach(i=>state.lastHits.add(i));state.events.push(...r.events);});state.spins--;state.lastScore=total;state.score+=total;state.events.push(`SPIN_FINISHED total=${total}`);state.grid=grid;if(state.score>=state.target){const baseReward=6,spinBonus=state.spins*2,reward=baseReward+spinBonus,before=state.coins;state.coins+=reward;state.reward={baseReward,remaining:state.spins,spinBonus,reward,before,after:state.coins};state.events.push(`STAGE_${state.stage+1}_WON reward=${reward} coins`);}else if(state.spins===0)state.events.push(`STAGE_${state.stage+1}_LOST`);render();}
function nextStage(){if(state.score<state.target||state.runComplete)return;if(state.stage>=STAGES.length-1){state.runComplete=true;render();return;}state.stage++;state.score=0;state.target=STAGES[state.stage];state.spins=8;state.lastScore=0;state.lastHits=new Set();state.breakdown=[];state.reward=null;state.grid=null;state.events=[`STAGE_${state.stage+1}_START target=${state.target}`];render();window.scrollTo({top:0,behavior:'smooth'});}
function renderGrid(){const el=document.querySelector('#grid'),g=state.grid||Array(9).fill(null);el.innerHTML=g.map((id,i)=>id?`<div class="cell ${state.lastHits.has(i)?'hit':''}"><div class="icon">${SYMBOLS[id].icon}</div><div class="name">${SYMBOLS[id].name}</div></div>`:`<div class="cell"><div class="icon">?</div><div class="name">empty</div></div>`).join('');}
function renderBreakdown(){const el=document.querySelector('#scoreBreakdown');if(!state.breakdown.length){el.innerHTML='<div class="empty-breakdown">После Spin здесь будет расчёт очков по каждой строке.</div>';return;}el.innerHTML=state.breakdown.map(x=>`<div class="break-row ${x.score?'win':'lose'}"><div><span class="row-name">Ряд ${x.row}</span><b>${x.symbols}</b></div><div class="calc"><strong>${x.title}</strong><span>${x.formula}</span>${x.notes?.length?`<small>${x.notes.join(' · ')}</small>`:''}</div><div class="line-score">+${x.score}</div></div>`).join('')+`<div class="spin-total"><span>Итого за Spin</span><strong>+${state.lastScore}</strong></div>`;}
function renderReward(){const el=document.querySelector('#rewardPanel');if(state.runComplete){el.classList.remove('hidden');el.innerHTML=`<h2>Prototype Run Complete</h2><p>Ты прошёл все ${STAGES.length} этапов текущего тестового режима.</p><div class="reward-grid"><span>Финальный Stage</span><strong>${STAGES.length}</strong><span>Coins</span><strong>${state.coins} 🪙</strong></div><button class="next-stage-btn" id="restartFullRunBtn">Начать новый run</button>`;return;}if(!state.reward){el.classList.add('hidden');el.innerHTML='';return;}const r=state.reward,last=state.stage===STAGES.length-1;el.classList.remove('hidden');el.innerHTML=`<h2>Stage ${state.stage+1} Complete</h2><div class="reward-grid"><span>Цель достигнута</span><strong>${state.score} / ${state.target}</strong><span>Базовая награда</span><strong>+${r.baseReward} 🪙</strong><span>Осталось Spin: ${r.remaining} × 2</span><strong>+${r.spinBonus} 🪙</strong><span>Итого Coins</span><strong>+${r.reward} 🪙</strong><span>Баланс</span><strong>${r.before} → ${r.after} 🪙</strong></div><button class="next-stage-btn" id="nextStageBtn">${last?'Завершить тестовый run':`Перейти на Stage ${state.stage+2} — Target ${STAGES[state.stage+1]}`}</button><p class="help-text block">Твой Symbol Pool, Modifiers и Coins сохранятся. Encounter Score сбросится в 0, Spins восстановятся до 8.</p>`;}
function renderDevControls(){document.querySelector('#symbolButtons').innerHTML=Object.keys(SYMBOLS).map(id=>{const c=state.pool[id]||0,s=SYMBOLS[id];return`<button class="dev-symbol" data-symbol="${id}"><span class="dev-main">+ ${s.icon} ${s.name}</span><span class="dev-count">Сейчас ×${c} → после нажатия ×${c+1}</span><span class="dev-effect">Добавляет 1 копию в пул. Больше копий = выше шанс выпадения.</span></button>`;}).join('');document.querySelector('#modifierButtons').innerHTML=Object.keys(MODIFIERS).map(id=>{const on=state.modifiers.has(id),m=MODIFIERS[id];return`<button class="dev-mod ${on?'active':''}" data-modifier="${id}"><span class="dev-main">${m.name} <b>${on?'ON':'OFF'}</b></span><span class="dev-effect">${m.description}</span></button>`;}).join('');}
function render(){renderGrid();renderBreakdown();renderReward();renderDevControls();document.querySelector('#stageText').textContent=`Stage ${state.stage+1} / ${STAGES.length}`;document.querySelector('#nextTargetText').textContent=state.stage<STAGES.length-1?STAGES[state.stage+1]:'—';document.querySelector('#targetText').textContent=`${state.score} / ${state.target}`;document.querySelector('#scoreProgress').style.width=`${Math.min(100,state.score/state.target*100)}%`;document.querySelector('#spinsText').textContent=state.spins;document.querySelector('#coinsText').textContent=state.coins;document.querySelector('#lastScoreText').textContent=`+${state.lastScore}`;document.querySelector('#seedInput').value=state.seed;document.querySelector('#spinBtn').disabled=state.spins<=0||state.score>=state.target||state.runComplete;document.querySelector('#resultText').textContent=state.runComplete?'Тестовый run завершён.':state.score>=state.target?`Stage ${state.stage+1} пройден — переход ниже.`:state.spins===0?`Stage ${state.stage+1} проигран: Spin закончились раньше Target.`:`Stage ${state.stage+1}: ${state.score} / ${state.target}`;document.querySelector('#poolList').innerHTML=Object.entries(state.pool).filter(([,c])=>c>0).map(([id,c])=>`<div class="pool-row"><div><span>${SYMBOLS[id].icon} ${SYMBOLS[id].name}</span><small>${SYMBOLS[id].description}</small></div><strong>×${c}</strong></div>`).join('');document.querySelector('#modifierList').innerHTML=state.modifiers.size?[...state.modifiers].map(id=>`<div class="modifier-item"><strong>${MODIFIERS[id].name}</strong><small>${MODIFIERS[id].description}</small></div>`).join(''):'<span class="muted">Нет modifiers.</span>';document.querySelector('#eventLog').innerHTML=state.events.slice().reverse().map(e=>`<li>${e}</li>`).join('');}
function log(m){state.events.push(m);if(state.events.length>50)state.events.shift();}
function addSymbol(id){state.pool[id]=(state.pool[id]||0)+1;log(`DEV: ${SYMBOLS[id].name} added to pool, now ×${state.pool[id]}`);render();}
function toggleModifier(id){state.modifiers.has(id)?state.modifiers.delete(id):state.modifiers.add(id);log(`DEV: ${MODIFIERS[id].name} ${state.modifiers.has(id)?'ON':'OFF'}`);render();}
function boot(seed=12345){state=makeState(seed);render();}
document.querySelector('#spinBtn').onclick=spin;document.querySelector('#restartSeedBtn').onclick=()=>boot(document.querySelector('#seedInput').value);document.querySelector('#newSeedBtn').onclick=()=>boot(Date.now()>>>0);document.querySelector('#resetRunBtn').onclick=()=>boot(state.seed);document.querySelector('#addCoinsBtn').onclick=()=>{state.coins+=20;log('DEV: +20 Coins');render();};document.querySelector('#clearLogBtn').onclick=()=>{state.events=[];render();};document.querySelector('#forceJackpotBtn').onclick=()=>{forcedGrid=['cherry','cherry','wild','diamond','diamond','wild','bomb','bomb','wild'];log('DEV: forced test grid armed');render();};document.querySelector('#symbolButtons').onclick=e=>{const b=e.target.closest('[data-symbol]');if(b)addSymbol(b.dataset.symbol);};document.querySelector('#modifierButtons').onclick=e=>{const b=e.target.closest('[data-modifier]');if(b)toggleModifier(b.dataset.modifier);};document.querySelector('#rewardPanel').onclick=e=>{if(e.target.id==='nextStageBtn')nextStage();if(e.target.id==='restartFullRunBtn')boot(state.seed);};boot();